# Generated by Django 3.2.5 on 2021-09-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='sample.jpg', upload_to='profile_pics'),
        ),
    ]
